In [80]:
import torch
print(torch.__version__)

2.9.1+cu128


In [81]:
!nvidia-smi

Thu Dec  4 00:05:13 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.95.05              Driver Version: 580.95.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   53C    P3            752W /   35W |      15MiB /   4096MiB |     11%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### INTRODUCTION TO TENSORS
Creating Tensors

In [82]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [83]:
scalar.ndim

0

In [84]:
scalar.item()

7

In [85]:
scalar.shape

torch.Size([])

In [86]:
#Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [87]:
vector.ndim

1

In [88]:
vector.shape

torch.Size([2])

In [89]:
#MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [90]:
MATRIX.ndim

2

In [91]:
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [92]:
MATRIX.shape

torch.Size([2, 2])

In [93]:
#TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR, TENSOR.shape

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]),
 torch.Size([1, 3, 3]))

In [94]:
TENSOR.ndim

3

In [95]:
TENSOR.shape

torch.Size([1, 3, 3])

In [96]:
x = torch.squeeze(TENSOR)
x, x.shape

(tensor([[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]),
 torch.Size([3, 3]))

In [97]:
print(TENSOR[0])

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


In [98]:
TENSOR = torch.tensor([[[[1, 2, 3, 4],
                          [2, 4, 5, 8],
                          [3, 9, 2, 7],
                          [4, 3, 6, 1]]]])
TENSOR

tensor([[[[1, 2, 3, 4],
          [2, 4, 5, 8],
          [3, 9, 2, 7],
          [4, 3, 6, 1]]]])

In [99]:
TENSOR.ndim

4

In [100]:
TENSOR.shape

torch.Size([1, 1, 4, 4])

In [101]:
TENSOR = torch.tensor([[[[[1, 2, 3, 4],
                          [2, 4, 5, 8],
                          [3, 9, 2, 7],
                          [4, 3, 6, 1],
                          [4, 3, 6, 1]]]]])

In [102]:
TENSOR.ndim

5

In [103]:
TENSOR.shape

torch.Size([1, 1, 1, 5, 4])

In [104]:
TENSOR = torch.tensor([[[[[1, 2, 3, 4, 1],
                          [2, 4, 5, 8, 1],
                          [3, 9, 2, 7, 1],
                          [4, 3, 6, 1, 1],
                          [4, 3, 6, 1, 1]]]]])

In [105]:
TENSOR.ndim

5

In [106]:
TENSOR.shape

torch.Size([1, 1, 1, 5, 5])

In [107]:
TENSOR = torch.tensor([[[[1, 2, 3, 4, 1],
                          [2, 4, 5, 8, 1],
                          [3, 9, 2, 7, 1],
                          [4, 3, 6, 1, 1],
                          [4, 3, 6, 1, 1]]]])

In [108]:
TENSOR.ndim

4

In [109]:
TENSOR.shape

torch.Size([1, 1, 5, 5])

In [110]:
TENSOR = torch.tensor([[[[1, 2, 3, 4, 1],
                          [2, 4, 5, 8, 1],
                          [3, 9, 2, 7, 1],
                          [4, 3, 6, 1, 1],
                          [4, 3, 6, 1, 1],
                          [4, 3, 6, 1, 1]]]])

In [111]:
TENSOR.ndim

4

In [112]:
TENSOR.shape

torch.Size([1, 1, 6, 5])

RANDOM TENSORS

In [113]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5929, 0.2877, 0.0616, 0.4166],
        [0.1141, 0.7953, 0.9961, 0.0656],
        [0.4064, 0.4822, 0.1378, 0.5253]])

In [114]:
random_tensor.ndim

2

In [115]:
print(random_tensor.shape)

torch.Size([3, 4])


In [116]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.5384, 0.3603, 0.6136, 0.7256],
         [0.0128, 0.9888, 0.3707, 0.7040],
         [0.4942, 0.1236, 0.1744, 0.8708]]])

In [117]:
print(random_tensor.ndim)

3


In [118]:
print(random_tensor.shape)

torch.Size([1, 3, 4])


In [119]:
#Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3))  #height, width and color channels with colors (R, G, B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [120]:
print(random_image_tensor)

tensor([[[0.8000, 0.2300, 0.0546],
         [0.8213, 0.5975, 0.2936],
         [0.1766, 0.1179, 0.4865],
         ...,
         [0.9098, 0.4661, 0.3341],
         [0.5283, 0.7720, 0.5761],
         [0.9943, 0.3641, 0.2222]],

        [[0.3852, 0.0595, 0.1765],
         [0.0045, 0.4999, 0.1244],
         [0.2248, 0.2299, 0.8597],
         ...,
         [0.9386, 0.6852, 0.9956],
         [0.4548, 0.8830, 0.2467],
         [0.4365, 0.2600, 0.9103]],

        [[0.2899, 0.8622, 0.5197],
         [0.5948, 0.8673, 0.4520],
         [0.9770, 0.8655, 0.9510],
         ...,
         [0.6792, 0.6012, 0.4380],
         [0.8643, 0.6081, 0.7690],
         [0.6543, 0.2776, 0.6247]],

        ...,

        [[0.2641, 0.1526, 0.7568],
         [0.5057, 0.4698, 0.7447],
         [0.3371, 0.8738, 0.0438],
         ...,
         [0.9458, 0.9625, 0.7209],
         [0.0312, 0.6224, 0.2440],
         [0.4314, 0.6026, 0.8484]],

        [[0.9875, 0.6642, 0.5310],
         [0.5312, 0.1462, 0.9792],
         [0.

In [121]:
random_tensor = torch.rand(5, 5, 10)
random_tensor

tensor([[[0.5033, 0.0266, 0.7537, 0.0856, 0.9517, 0.2247, 0.3095, 0.7396,
          0.2089, 0.5479],
         [0.9201, 0.6470, 0.0056, 0.9198, 0.7665, 0.3446, 0.2131, 0.8715,
          0.7881, 0.5902],
         [0.5171, 0.1827, 0.5912, 0.0102, 0.3597, 0.9907, 0.2937, 0.9679,
          0.5842, 0.2351],
         [0.0482, 0.8946, 0.9130, 0.9307, 0.5343, 0.0907, 0.0488, 0.9037,
          0.6863, 0.4910],
         [0.4923, 0.7269, 0.7789, 0.2806, 0.5233, 0.2811, 0.2893, 0.5611,
          0.2582, 0.2899]],

        [[0.0944, 0.8499, 0.5702, 0.6505, 0.4818, 0.0853, 0.7800, 0.3984,
          0.4269, 0.7736],
         [0.2328, 0.7588, 0.3193, 0.1345, 0.9501, 0.3318, 0.0621, 0.5803,
          0.4131, 0.9527],
         [0.1297, 0.2533, 0.9726, 0.0629, 0.8431, 0.9068, 0.0648, 0.1613,
          0.7703, 0.5400],
         [0.1601, 0.2977, 0.7431, 0.3987, 0.7360, 0.1749, 0.5691, 0.8267,
          0.7346, 0.7593],
         [0.9627, 0.0780, 0.4368, 0.5499, 0.5303, 0.1574, 0.9578, 0.7159,
          0.384

In [122]:
print(random_tensor.shape)
print(random_tensor.ndim)

torch.Size([5, 5, 10])
3


### ZEROS AND ONES

In [123]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [124]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [125]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [127]:
random_tensor

tensor([[[0.5033, 0.0266, 0.7537, 0.0856, 0.9517, 0.2247, 0.3095, 0.7396,
          0.2089, 0.5479],
         [0.9201, 0.6470, 0.0056, 0.9198, 0.7665, 0.3446, 0.2131, 0.8715,
          0.7881, 0.5902],
         [0.5171, 0.1827, 0.5912, 0.0102, 0.3597, 0.9907, 0.2937, 0.9679,
          0.5842, 0.2351],
         [0.0482, 0.8946, 0.9130, 0.9307, 0.5343, 0.0907, 0.0488, 0.9037,
          0.6863, 0.4910],
         [0.4923, 0.7269, 0.7789, 0.2806, 0.5233, 0.2811, 0.2893, 0.5611,
          0.2582, 0.2899]],

        [[0.0944, 0.8499, 0.5702, 0.6505, 0.4818, 0.0853, 0.7800, 0.3984,
          0.4269, 0.7736],
         [0.2328, 0.7588, 0.3193, 0.1345, 0.9501, 0.3318, 0.0621, 0.5803,
          0.4131, 0.9527],
         [0.1297, 0.2533, 0.9726, 0.0629, 0.8431, 0.9068, 0.0648, 0.1613,
          0.7703, 0.5400],
         [0.1601, 0.2977, 0.7431, 0.3987, 0.7360, 0.1749, 0.5691, 0.8267,
          0.7346, 0.7593],
         [0.9627, 0.0780, 0.4368, 0.5499, 0.5303, 0.1574, 0.9578, 0.7159,
          0.384

In [128]:
zeroes_tensors = torch.zeros_like(input=random_tensor)
zeroes_tensors

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.,

In [129]:
zeroes_tensors = torch.zeros_like(input=random_tensor[0])
zeroes_tensors

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [130]:
zeroes_tensors = torch.zeros_like(input=random_tensor[0][1])
zeroes_tensors

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [131]:
zeroes_tensors = torch.zeros_like(input=random_tensor[0][1][2])
zeroes_tensors

tensor(0.)

### Tensors Datatypes

NOTE --> Tensor Datatype is one of the 3 big errors one runs into with PyTorch and Deep Learning:




    1) Tensors of not the right Datatype
    2) Tensors not the right shape
    3) Tensors not on the right device

In [132]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [133]:
float_32_tensor.dtype

torch.float32

In [134]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [135]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [136]:
tensor_mult = float_16_tensor * float_32_tensor
tensor_mult

tensor([ 9., 36., 81.])

In [137]:
tensor_mult_2 = float_32_tensor * float_64_tensor
tensor_mult_2

tensor([ 9., 36., 81.], dtype=torch.float64)

In [138]:
tensor_mult.dtype

torch.float32

In [139]:
tensor_a = torch.rand(3, 4)
print(tensor_a)
tensor_b = torch.rand(3, 4)
print(tensor_b)
result = tensor_a * tensor_b
print(result)
print(result.dtype)

tensor([[0.9024, 0.5344, 0.4754, 0.9979],
        [0.6556, 0.2195, 0.5434, 0.3479],
        [0.0940, 0.7673, 0.2742, 0.4624]])
tensor([[0.7199, 0.0691, 0.3016, 0.9129],
        [0.4600, 0.5406, 0.0672, 0.7307],
        [0.4034, 0.2640, 0.9450, 0.9357]])
tensor([[0.6496, 0.0369, 0.1434, 0.9110],
        [0.3016, 0.1187, 0.0365, 0.2542],
        [0.0379, 0.2026, 0.2591, 0.4327]])
torch.float32


In [140]:
# tensor_a = torch.rand(3, 4)
# print(tensor_a)
# tensor_b = torch.rand(4, 3)
# print(tensor_b)
# result = tensor_a * tensor_b
# print(result)
# print(result.dtype)

In [141]:
embedding = torch.rand(10, 512)
print(embedding.shape)
scale = torch.rand(512)
print(scale.shape)

result = embedding * scale   # broadcasting
print(result)
print(result.shape)


torch.Size([10, 512])
torch.Size([512])
tensor([[0.1414, 0.0284, 0.0628,  ..., 0.1505, 0.0601, 0.1157],
        [0.2371, 0.0285, 0.0065,  ..., 0.4588, 0.3482, 0.1368],
        [0.2825, 0.0330, 0.0378,  ..., 0.3375, 0.1712, 0.1394],
        ...,
        [0.1871, 0.0261, 0.0785,  ..., 0.1524, 0.0498, 0.0359],
        [0.1168, 0.0048, 0.0386,  ..., 0.0249, 0.3444, 0.0209],
        [0.2590, 0.0377, 0.0168,  ..., 0.1705, 0.3157, 0.0909]])
torch.Size([10, 512])


### Tensor Attributes
& Note: `tensor.size()` and `tensor.shape` perform the same function, just that `size()` is a function and `shape` is an attribute

In [142]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9126, 0.5471, 0.3691, 0.0279],
        [0.6630, 0.9305, 0.6898, 0.0944],
        [0.6566, 0.8911, 0.3938, 0.4422]])

In [143]:
print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device is on : {some_tensor.device}")

tensor([[0.9126, 0.5471, 0.3691, 0.0279],
        [0.6630, 0.9305, 0.6898, 0.0944],
        [0.6566, 0.8911, 0.3938, 0.4422]])
DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device is on : cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [144]:
#Create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [145]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [146]:
# Subtract the tensor by 10
tensor - 10

tensor([-9, -8, -7])

### Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise Multiplication

2. Matrix Multiplication

In [147]:
tensor
element_wise = tensor*tensor
matrix_mult = torch.matmul(tensor, tensor)
print(element_wise)
print(matrix_mult)

tensor([1, 4, 9])
tensor(14)


### SHAPE ERRORS

In [148]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
# torch.mm(tensor_A, tensor_B)

In [149]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues we can manipulate the shape of one of our tensors using a **transpose**

In [150]:
tensor_B = tensor_B.T

In [151]:
torch.mm(tensor_A, tensor_B)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [152]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### Tensor Aggregation (Min, Max, Sum, Mean)

In [153]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [154]:
x.min()

tensor(0)

In [155]:
x.max()

tensor(90)

In [156]:
x.type(torch.float32).mean()  # Note : - the torch.mean() function requires a tensor of float32

tensor(45.)

### Reshaping, Stacking, Squeezing and Unsqueezing Tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Retrun a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [157]:
import torch
x = torch.arange(1., 10.)

In [158]:
# Reshape
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [159]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [160]:
#Stack
x_stacked_1 = torch.stack([x, x, x, x], dim=0)
x_stacked_1

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [161]:
x_stacked_2 = torch.stack([x, x, x, x], dim=1)
x_stacked_2

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [162]:
x_stacked_3 = torch.stack([x, x, x, x, x], dim=0)
x_stacked_3

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [163]:
x = torch.zeros(2, 1, 2, 1, 2)
x, x.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [164]:
y = torch.squeeze(x)
y, y.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [165]:
y = torch.squeeze(x, 0)
y, y.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [166]:
y = torch.squeeze(x, 1)
y, y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))